# Generated by Django 4.1.5 on 2024-11-15 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("telefone", models.CharField(max_length=20)),
                ("cpf", models.CharField(max_length=11, unique=True)),
                ("rg", models.CharField(max_length=9, unique=True)),
                ("cep", models.CharField(max_length=8)),
                (
                    "lead",
                    models.CharField(
                        choices=[
                            ("indicacao", "Indicação"),
                            ("instagram", "Instagram"),
                            ("anuncio", "Anúncio"),
                            ("recorrente", "Recorrente"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                (
                    "material",
                    models.CharField(
                        choices=[
                            ("malhaalgodao", "Malha Algodão"),
                            ("cottonelastano", "Cotton Elastano"),
                            ("moletomstrong", "Moletom Strong"),
                            ("moletombasic", "Moletom Basic"),
                            ("dryfit", "Dry Fit"),
                            ("poliamida", "Poliamida"),
                            ("malhacanelada", "Malha Canelada"),
                        ],
                        max_length=15,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=20, unique=True)),
                ("data_pedido", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preparacao", "Preparação"),
                            ("compra", "Compra"),
                            ("corte", "Corte"),
                            ("personalizacao", "Personalização"),
                            ("costura", "Costura"),
                            ("embalagem", "Embalagem"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kq_app.cliente"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrdemDeServico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField(blank=True, null=True)),
                ("cor", models.CharField(max_length=30)),
                ("quantidade", models.IntegerField(default=0)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("pp_masculino", models.IntegerField(default=0)),
                ("p_masculino", models.IntegerField(default=0)),
                ("m_masculino", models.IntegerField(default=0)),
                ("g_masculino", models.IntegerField(default=0)),
                ("gg_masculino", models.IntegerField(default=0)),
                ("xg_masculino", models.IntegerField(default=0)),
                ("esp_masculino", models.IntegerField(default=0)),
                ("pp_feminino", models.IntegerField(default=0)),
                ("p_feminino", models.IntegerField(default=0)),
                ("m_feminino", models.IntegerField(default=0)),
                ("g_feminino", models.IntegerField(default=0)),
                ("gg_feminino", models.IntegerField(default=0)),
                ("xg_feminino", models.IntegerField(default=0)),
                ("esp_feminino", models.IntegerField(default=0)),
                ("bordado", models.BooleanField(default=False)),
                ("estampa", models.BooleanField(default=False)),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordens_servico",
                        to="kq_app.pedido",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kq_app.produto"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Custo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("materia_prima", "Matéria-prima"),
                            ("estampador", "Estampador"),
                            ("estampa", "Estampa"),
                            ("bordado", "Bordado"),
                            ("costura", "Costura"),
                            ("transporte", "Transporte"),
                            ("frete", "Frete"),
                            ("sublimacao", "Sublimação"),
                            ("terceirizado", "Terceirizado"),
                            ("retrabalho", "Retrabalho"),
                            ("imposto", "Imposto"),
                            ("vendedor", "Vendedor"),
                        ],
                        max_length=15,
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data_vencimento", models.DateField(blank=True, null=True)),
                (
                    "status_pagamento",
                    models.CharField(
                        choices=[("pendente", "Pendente"), ("pago", "Pago")],
                        default="pendente",
                        max_length=10,
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custos",
                        to="kq_app.pedido",
                    ),
                ),
            ],
        ),
    ]
