# Generated by Django 4.1.5 on 2024-12-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kq_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="endereco_completo",
            field=models.CharField(default="Endereço não informado", max_length=100),
        ),
        migrations.AddField(
            model_name="ordemdeservico",
            name="arte",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ordemdeservico",
            name="compra",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ordemdeservico",
            name="corte",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ordemdeservico",
            name="costura",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ordemdeservico",
            name="embalagem",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ordemdeservico",
            name="estampa_fase",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ordemdeservico",
            name="finalizado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ordemdeservico",
            name="impressao",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ordemdeservico",
            name="mockup",
            field=models.ImageField(blank=True, null=True, upload_to="mockups/"),
        ),
        migrations.AddField(
            model_name="ordemdeservico",
            name="personalizacao",
            field=models.ImageField(
                blank=True, null=True, upload_to="personalizacoes/"
            ),
        ),
        migrations.AddField(
            model_name="ordemdeservico",
            name="prazo",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="cep",
            field=models.CharField(default="00000000", max_length=8),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="email",
            field=models.EmailField(default="email@exemplo.com", max_length=254),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="lead",
            field=models.CharField(
                choices=[
                    ("indicacao", "Indicação"),
                    ("instagram", "Instagram"),
                    ("anuncio", "Anúncio"),
                    ("recorrente", "Recorrente"),
                    ("naoinformado", "Não Informado"),
                ],
                default="naoinformado",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="nome",
            field=models.CharField(default="Nome não informado", max_length=100),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="telefone",
            field=models.CharField(default="0000000000", max_length=20),
        ),
        migrations.AlterField(
            model_name="custo",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("materia_prima", "Matéria-prima"),
                    ("estampador", "Estampador"),
                    ("estampa", "Estampa"),
                    ("bordado", "Bordado"),
                    ("costura", "Costura"),
                    ("transporte", "Transporte"),
                    ("frete", "Frete"),
                    ("sublimacao", "Sublimação"),
                    ("terceirizado", "Terceirizado"),
                    ("retrabalho", "Retrabalho"),
                    ("imposto", "Imposto"),
                    ("vendedor", "Vendedor"),
                ],
                default="materia_prima",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="custo",
            name="valor",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="ordemdeservico",
            name="cor",
            field=models.CharField(default="Indefinido", max_length=30),
        ),
        migrations.AlterField(
            model_name="ordemdeservico",
            name="descricao",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="ordemdeservico",
            name="valor",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="status",
            field=models.CharField(
                choices=[
                    ("preparacao", "Preparação"),
                    ("compra", "Compra"),
                    ("corte", "Corte"),
                    ("personalizacao", "Personalização"),
                    ("costura", "Costura"),
                    ("embalagem", "Embalagem"),
                ],
                default="preparacao",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="material",
            field=models.CharField(
                choices=[
                    ("malhaalgodao", "Malha Algodão"),
                    ("cottonelastano", "Cotton Elastano"),
                    ("moletomstrong", "Moletom Strong"),
                    ("moletombasic", "Moletom Basic"),
                    ("dryfit", "Dry Fit"),
                    ("poliamida", "Poliamida"),
                    ("malhacanelada", "Malha Canelada"),
                ],
                default="malhaalgodao",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="nome",
            field=models.CharField(
                choices=[
                    ("camiseta", "Camiseta"),
                    ("moletom_canguru", "Moletom Canguru"),
                    ("moletom_careca", "Moletom Careca"),
                    ("jaqueta_college", "Jaqueta College"),
                    ("calca", "Calça"),
                    ("shorts", "Shorts"),
                    ("top", "Top"),
                    ("cropped", "Cropped"),
                    ("regata", "Regata"),
                    ("camisa_polo", "Camisa Polo"),
                    ("ecobag", "Ecobag"),
                    ("outro", "Outro"),
                ],
                default="outro",
                max_length=100,
            ),
        ),
    ]
