# Generated by Django 4.1.5 on 2024-12-19 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("kq_app", "0005_ordemdeservico_materia_prima_produto_rendimento"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordemdeservico",
            name="numero",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="material",
            name="nome",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="numero",
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="produto",
            name="rendimento",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="produto",
            name="tipo",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="kq_app.tipoproduto",
            ),
        ),
        migrations.AlterField(
            model_name="tipoproduto",
            name="nome",
            field=models.CharField(max_length=100),
        ),
    ]
