# Generated by Django 4.1.5 on 2024-12-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kq_app", "0006_ordemdeservico_numero_alter_material_nome_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="numero",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
