# Generated by Django 4.1.5 on 2025-03-02 15:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("kq_app", "0007_cliente_numero"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.IntegerField(default=0, verbose_name="Quantidade"),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "localizacao",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        null=True,
                        verbose_name="Localização",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estoque",
                "verbose_name_plural": "Estoques",
            },
        ),
        migrations.CreateModel(
            name="Pagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_pagamento",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data de Pagamento",
                    ),
                ),
                (
                    "valor_pago",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor Pago"
                    ),
                ),
                (
                    "forma_pagamento",
                    models.CharField(max_length=50, verbose_name="Forma de Pagamento"),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="Observações"
                    ),
                ),
                (
                    "numero_parcelas",
                    models.IntegerField(default=1, verbose_name="Número de Parcelas"),
                ),
                (
                    "data_vencimento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Vencimento"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pagamento",
                "verbose_name_plural": "Pagamentos",
            },
        ),
        migrations.AlterModelOptions(
            name="cliente",
            options={
                "ordering": ["nome"],
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
            },
        ),
        migrations.AlterModelOptions(
            name="custo",
            options={"verbose_name": "Custo", "verbose_name_plural": "Custos"},
        ),
        migrations.AlterModelOptions(
            name="ordemdeservico",
            options={
                "verbose_name": "Ordem de Serviço",
                "verbose_name_plural": "Ordens de Serviço",
            },
        ),
        migrations.AlterModelOptions(
            name="pedido",
            options={
                "ordering": ["-data_criacao"],
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
            },
        ),
        migrations.AlterModelOptions(
            name="produto",
            options={
                "ordering": ["nome"],
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
            },
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="cep",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="cpf",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="endereco_completo",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="lead",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="numero",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="rg",
        ),
        migrations.RemoveField(
            model_name="custo",
            name="data_vencimento",
        ),
        migrations.RemoveField(
            model_name="custo",
            name="pedido",
        ),
        migrations.RemoveField(
            model_name="custo",
            name="status_pagamento",
        ),
        migrations.RemoveField(
            model_name="ordemdeservico",
            name="arte",
        ),
        migrations.RemoveField(
            model_name="ordemdeservico",
            name="bordado",
        ),
        migrations.RemoveField(
            model_name="ordemdeservico",
            name="compra",
        ),
        migrations.RemoveField(
            model_name="ordemdeservico",
            name="cor",
        ),
        migrations.RemoveField(
            model_name="ordemdeservico",
            name="corte",
        ),
        migrations.RemoveField(
            model_name="ordemdeservico",
            name="costura",
        ),
        migrations.RemoveField(
            model_name="ordemdeservico",
            name="descricao",
        ),
        migrations.RemoveField(
            model_name="ordemdeservico",
            name="embalagem",
        ),
        migrations.RemoveField(
            model_name="ordemdeservico",
            name="esp_feminino",
        ),
        migrations.RemoveField(
            model_name="ordemdeservico",
            name="esp_masculino",
        ),
        migrations.RemoveField(
            model_name="ordemdeservico",
            name="estampa",
        ),
        migrations.RemoveField(
            model_name="ordemdeservico",
            name="estampa_fase",
        ),
        migrations.RemoveField(
            model_name="ordemdeservico",
            name="finalizado",
        ),
        migrations.RemoveField(
            model_name="ordemdeservico",
            name="g_feminino",
        ),
        migrations.RemoveField(
            model_name="ordemdeservico",
            name="g_masculino",
        ),
        migrations.RemoveField(
            model_name="ordemdeservico",
            name="gg_feminino",
        ),
        migrations.RemoveField(
            model_name="ordemdeservico",
            name="gg_masculino",
        ),
        migrations.RemoveField(
            model_name="ordemdeservico",
            name="impressao",
        ),
        migrations.RemoveField(
            model_name="ordemdeservico",
            name="m_feminino",
        ),
        migrations.RemoveField(
            model_name="ordemdeservico",
            name="m_masculino",
        ),
        migrations.RemoveField(
            model_name="ordemdeservico",
            name="materia_prima",
        ),
        migrations.RemoveField(
            model_name="ordemdeservico",
            name="numero",
        ),
        migrations.RemoveField(
            model_name="ordemdeservico",
            name="p_feminino",
        ),
        migrations.RemoveField(
            model_name="ordemdeservico",
            name="p_masculino",
        ),
        migrations.RemoveField(
            model_name="ordemdeservico",
            name="pp_feminino",
        ),
        migrations.RemoveField(
            model_name="ordemdeservico",
            name="pp_masculino",
        ),
        migrations.RemoveField(
            model_name="ordemdeservico",
            name="prazo",
        ),
        migrations.RemoveField(
            model_name="ordemdeservico",
            name="valor",
        ),
        migrations.RemoveField(
            model_name="ordemdeservico",
            name="xg_feminino",
        ),
        migrations.RemoveField(
            model_name="ordemdeservico",
            name="xg_masculino",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="data_pedido",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="numero",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="material",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="rendimento",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="tipo",
        ),
        migrations.AddField(
            model_name="cliente",
            name="cpf_cnpj",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="CPF/CNPJ"
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="data_cadastro",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Data de Cadastro"
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="endereco",
            field=models.TextField(blank=True, null=True, verbose_name="Endereço"),
        ),
        migrations.AddField(
            model_name="custo",
            name="data",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Data"
            ),
        ),
        migrations.AddField(
            model_name="custo",
            name="descricao",
            field=models.CharField(
                default="Custo adicional", max_length=200, verbose_name="Descrição"
            ),
        ),
        migrations.AddField(
            model_name="custo",
            name="ordem_de_servico",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="kq_app.ordemdeservico",
                verbose_name="Ordem de Serviço",
            ),
        ),
        migrations.AddField(
            model_name="ordemdeservico",
            name="data_conclusao",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Conclusão"
            ),
        ),
        migrations.AddField(
            model_name="ordemdeservico",
            name="observacoes",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Observações"
            ),
        ),
        migrations.AddField(
            model_name="ordemdeservico",
            name="preco_unitario",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Preço Unitário",
            ),
        ),
        migrations.AddField(
            model_name="ordemdeservico",
            name="responsavel",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                null=True,
                verbose_name="Responsável",
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="data_criacao",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Data de Criação"
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="data_entrega",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Entrega"
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="observacoes",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Observações"
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="valor_total",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=12, verbose_name="Valor Total"
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="codigo_barras",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Código de Barras"
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="descricao",
            field=models.TextField(
                blank=True, default="descrição", null=True, verbose_name="Descrição"
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="nome",
            field=models.CharField(
                default="nome", max_length=200, verbose_name="Nome do Produto"
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="preco",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Preço"
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="unidade_medida",
            field=models.CharField(
                default="un", max_length=20, verbose_name="Unidade de Medida"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="nome",
            field=models.CharField(
                default="Cliente", max_length=200, verbose_name="Nome do Cliente"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="telefone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Telefone"
            ),
        ),
        migrations.AlterField(
            model_name="custo",
            name="tipo",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                null=True,
                verbose_name="Tipo de Custo",
            ),
        ),
        migrations.AlterField(
            model_name="custo",
            name="valor",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Valor"
            ),
        ),
        migrations.AlterField(
            model_name="ordemdeservico",
            name="pedido",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="kq_app.pedido",
                verbose_name="Pedido",
            ),
        ),
        migrations.AlterField(
            model_name="ordemdeservico",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="kq_app.produto",
                verbose_name="Produto",
            ),
        ),
        migrations.AlterField(
            model_name="ordemdeservico",
            name="quantidade",
            field=models.IntegerField(default=0, verbose_name="Quantidade"),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="kq_app.cliente",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="status",
            field=models.CharField(
                choices=[
                    ("novo", "Novo"),
                    ("em_producao", "Em Produção"),
                    ("aguardando_aprovacao", "Aguardando Aprovação"),
                    ("concluido", "Concluído"),
                    ("cancelado", "Cancelado"),
                ],
                default="novo",
                max_length=50,
                verbose_name="Status do Pedido",
            ),
        ),
        migrations.DeleteModel(
            name="Material",
        ),
        migrations.DeleteModel(
            name="TipoProduto",
        ),
        migrations.AddField(
            model_name="pagamento",
            name="pedido",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="kq_app.pedido",
                verbose_name="Pedido",
            ),
        ),
        migrations.AddField(
            model_name="estoque",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="kq_app.produto",
                verbose_name="Produto",
            ),
        ),
    ]
