# Generated by Django 4.1.5 on 2025-03-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kq_app", "0008_estoque_pagamento_alter_cliente_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="cep",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="CEP"
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="equipe",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Equipe"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="nome",
            field=models.CharField(max_length=200, verbose_name="Nome do Cliente"),
        ),
    ]
