# Generated by Django 4.1.5 on 2025-03-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kq_app", "0009_cliente_cep_cliente_equipe_alter_cliente_nome"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordemdeservico",
            name="data_conclusao",
        ),
        migrations.RemoveField(
            model_name="ordemdeservico",
            name="preco_unitario",
        ),
        migrations.RemoveField(
            model_name="ordemdeservico",
            name="responsavel",
        ),
        migrations.AddField(
            model_name="ordemdeservico",
            name="esp_feminino",
            field=models.IntegerField(default=0, verbose_name="ESP Feminino"),
        ),
        migrations.AddField(
            model_name="ordemdeservico",
            name="esp_masculino",
            field=models.IntegerField(default=0, verbose_name="ESP Masculino"),
        ),
        migrations.AddField(
            model_name="ordemdeservico",
            name="g_feminino",
            field=models.IntegerField(default=0, verbose_name="G Feminino"),
        ),
        migrations.AddField(
            model_name="ordemdeservico",
            name="g_masculino",
            field=models.IntegerField(default=0, verbose_name="G Masculino"),
        ),
        migrations.AddField(
            model_name="ordemdeservico",
            name="gg_feminino",
            field=models.IntegerField(default=0, verbose_name="GG Feminino"),
        ),
        migrations.AddField(
            model_name="ordemdeservico",
            name="gg_masculino",
            field=models.IntegerField(default=0, verbose_name="GG Masculino"),
        ),
        migrations.AddField(
            model_name="ordemdeservico",
            name="m_feminino",
            field=models.IntegerField(default=0, verbose_name="M Feminino"),
        ),
        migrations.AddField(
            model_name="ordemdeservico",
            name="m_masculino",
            field=models.IntegerField(default=0, verbose_name="M Masculino"),
        ),
        migrations.AddField(
            model_name="ordemdeservico",
            name="mockup",
            field=models.ImageField(
                blank=True, null=True, upload_to="mockups/", verbose_name="Mockup"
            ),
        ),
        migrations.AddField(
            model_name="ordemdeservico",
            name="p_feminino",
            field=models.IntegerField(default=0, verbose_name="P Feminino"),
        ),
        migrations.AddField(
            model_name="ordemdeservico",
            name="p_masculino",
            field=models.IntegerField(default=0, verbose_name="P Masculino"),
        ),
        migrations.AddField(
            model_name="ordemdeservico",
            name="pp_feminino",
            field=models.IntegerField(default=0, verbose_name="PP Feminino"),
        ),
        migrations.AddField(
            model_name="ordemdeservico",
            name="pp_masculino",
            field=models.IntegerField(default=0, verbose_name="PP Masculino"),
        ),
        migrations.AddField(
            model_name="ordemdeservico",
            name="xg_feminino",
            field=models.IntegerField(default=0, verbose_name="XG Feminino"),
        ),
        migrations.AddField(
            model_name="ordemdeservico",
            name="xg_masculino",
            field=models.IntegerField(default=0, verbose_name="XG Masculino"),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="cep",
            field=models.CharField(
                blank=True, max_length=9, null=True, verbose_name="CEP"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="equipe",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Equipe"
            ),
        ),
        migrations.AlterField(
            model_name="ordemdeservico",
            name="quantidade",
            field=models.IntegerField(default=1, verbose_name="Quantidade"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="descricao",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Descrição"
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="nome",
            field=models.CharField(max_length=200, verbose_name="Nome do Produto"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="preco",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Preço"
            ),
        ),
    ]
