# Generated by Django 4.1.5 on 2025-03-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kq_app", "0010_remove_ordemdeservico_data_conclusao_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="codigo_barras",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="descricao",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="preco",
        ),
        migrations.AddField(
            model_name="produto",
            name="material",
            field=models.CharField(
                default="Material", max_length=200, verbose_name="Material do Produto"
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="rendimento",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=10, verbose_name="Rendimento"
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="unidade_medida",
            field=models.CharField(
                choices=[("kg", "Kilograma"), ("metro", "Metro")],
                default="kg",
                max_length=10,
                verbose_name="Unidade de Medida",
            ),
        ),
    ]
