# Generated by Django 4.1.5 on 2025-03-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kq_app", "0012_alter_ordemdeservico_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordemdeservico",
            name="quantidade",
        ),
        migrations.AddField(
            model_name="ordemdeservico",
            name="preco_unitario",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Preço Unitário",
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="frete",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="Frete"
            ),
        ),
    ]
