# Generated by Django 4.1.5 on 2025-03-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kq_app", "0013_remove_ordemdeservico_quantidade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordemdeservico",
            name="quantidade_digitada",
            field=models.IntegerField(default=0, verbose_name="Quantidade Digitada"),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="status",
            field=models.CharField(
                choices=[
                    ("analise", "Análise"),
                    ("aprovado", "Aprovado"),
                    ("compra", "Compra"),
                    ("corte", "Corte"),
                    ("personalizacao", "Personalização"),
                    ("costura", "Costura"),
                    ("embalagem", "Embalagem"),
                    ("enviado", "Enviado"),
                ],
                default="novo",
                max_length=50,
                verbose_name="Status do Pedido",
            ),
        ),
    ]
