# Generated by Django 4.1.5 on 2025-03-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kq_app", "0014_ordemdeservico_quantidade_digitada_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordemdeservico",
            name="cor_tecido",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Cor do Tecido"
            ),
        ),
    ]
